#!/usr/bin/env php

<?php
$object = $argv[2];
$secretKey = $argv[1];
$cookie = urlencode('{"token":"' . $object . '","sig_hmac_sha1":"' . hash_hmac('sha1', $object, $secretKey) . '"}');
echo $cookie;
?>
